### ISSUE TITLE
advanceWindow() not working on Unix

### ISSUE THREAD

**Issue by andy-stanciu** [firejoust/mineflayer-GUI#13]
Any idea why advanceWindow() is working perfectly when I run a mineflayer bot on Windows (navigating through an in-game gui), but when I run the same bot on my Unix VM (same node, npm, mineflayer, and mineflayer-gui versions), the advanceWindow() method seems to time out.
```js
await new bot.gui.Query()
    .window(window)
    .matchBy('slot')
    .advanceWindow(12)
    .then(q => {
        return q.matchBy('slot').advanceWindow(15);
    })
    .then(q => {
        return q.matchBy('slot').mouseButton('left').clickItems(32);
    });
bot.closeWindow(window);
```

**Comment by firejoust** [comment]
Hmm not sure, might have something to do with the nested order of `.then`(s) being seen differently on windows vs unix. Maybe try:
```js
await new bot.gui.Query()
    .window(window)
    .matchBy('slot')
    .advanceWindow(12)
    .then(q => q
        .matchBy('slot')
        .advanceWindow(15)
        .then(q => q
            .matchBy('slot')
            .mouseButton('left')
            .clickItems(32)
        )
    )
bot.closeWindow(window);
```
This will make it clearer to the interpreter which promise is being passed where

Or alternatively, store the query and make separate function calls:
```js
const query = new bot.gui.Query()
    .window(window)
    .matchBy('slot')

const status$1 = await query
    .advanceWindow(12)

const status$2 = await query
    .matchBy('slot')
    .advanceWindow(15)

const status$3 = await query
    .matchBy('slot')
    .mouseButton('left')
    .clickItems(32)

bot.closeWindow(window);
```

**Comment by firejoust** [comment]
Also for a single query, the config will be saved between function calls. You can simplify your code like so if you want:
```js
const query =  new bot.gui.Query()

const status$1 = await query // left click is the default mouse button
    .window(window)
    .matchBy('slot')
    .getWindow(12, 15) // open window from slot 12, then open next window from slot 15

const status$2 = await query
    .clickItems(32)

bot.closeWindow(window);
```

**Comment by andy-stanciu** [comment]
Appreciate the help. I essentially already tried all of these, but none of them made a difference. Ended up "fixing" it on Unix by adding (short) wait times of 100ms in between each advanceWindow() call. Not sure why the behavior is different on Unix, nor why this fixed it though...let me know if you have any insight on this.
